$Common.login.UserInfo.Search
SELECT * FROM MEMBER_INFO WHERE USERID = :userid

$Common.Cart.Search
SELECT A.CART_NO, A.COURSE_NO, A.HOLE_NO, A.BLOCK_NO, A.CART_TYPE, A.CART_STATE, NVL(C.CADDIE_NAME, '-') AS CADDIE_NAME
  FROM CART_BLOCK A,
       (SELECT C.CART_NO, NVL(A.CADDIE_NAME, '-') AS CADDIE_NAME
          FROM VI_ALL_TEAMINFO A,
               (SELECT CART_NO, MAX(TEAM_NO) AS TEAM_NO, MIN(ID_NO) AS ID_NO
                  FROM VI_ALL_TEAMINFO
                 WHERE VISIT_DATE = TO_CHAR(SYSDATE, 'YYYYMMDD')
                 GROUP BY CART_NO) B, CART_WRAPPER C
         WHERE A.VISIT_DATE = TO_CHAR(SYSDATE, 'YYYYMMDD')
           AND A.CART_NO    = B.CART_NO
           AND A.TEAM_NO    = B.TEAM_NO
           AND A.ID_NO      = B.ID_NO
           AND A.CART_NO    = C.CART_ID )C
 WHERE A.CART_NO = C.CART_NO(+)
   AND A.HOLE_NO <> 0
   AND A.COURSE_NO = :course_no
   AND A.HOLE_NO = :hole_no
   
$Common.Cart2.Search
SELECT A.CART_NO, A.COURSE_NO, A.HOLE_NO, A.BLOCK_NO, A.CART_TYPE, A.CART_STATE, B.TEAM_NO,
       CASE WHEN LENGTH(NVL(B.CADDIE_NAME, '-')) > 2 THEN LTRIM(SUBSTR(NVL(B.CADDIE_NAME, '-') ,2, 5)) ELSE NVL(B.CADDIE_NAME, '-') END AS CADDIE_NAME
  FROM CART_BLOCK A, (SELECT CART_NO, MAX(CADDIE_NAME) CADDIE_NAME, MAX(TEAM_NO) TEAM_NO FROM VI_ALL_TEAMINFO WHERE VISIT_DATE = TO_CHAR(SYSDATE, 'YYYYMMDD') GROUP BY CART_NO) B,
       (SELECT C.CART_NO
          FROM VI_ALL_TEAMINFO A,
               (SELECT CART_NO, MAX(TEAM_NO) AS TEAM_NO, MIN(ID_NO) AS ID_NO
                  FROM VI_ALL_TEAMINFO
                 WHERE VISIT_DATE = TO_CHAR(SYSDATE, 'YYYYMMDD')
                 GROUP BY CART_NO) B, CART_WRAPPER C
         WHERE A.VISIT_DATE = TO_CHAR(SYSDATE, 'YYYYMMDD')
           AND A.CART_NO    = B.CART_NO
           AND A.TEAM_NO    = B.TEAM_NO
           AND A.ID_NO      = B.ID_NO
           AND A.CART_NO    = C.CART_ID ) C
 WHERE A.CART_NO = C.CART_NO(+)
   AND A.CART_NO = B.CART_NO(+)
   AND A.HOLE_NO <> 0
   AND A.COURSE_NO = :course_no
   AND A.HOLE_NO = :hole_no

$Common.Cart.Detail.Search
SELECT CART_NO, CADDIE_NO, TEAM_NO, CADDIE_NAME, START_TIME, ID_NO, VISIT_NAME, MEMBER_NAME
  FROM VI_ALL_TEAMINFO
 WHERE VISIT_DATE = TO_CHAR(SYSDATE, 'YYYYMMDD')
   AND CART_NO = :cart_no AND TEAM_NO = :team_no

$Common.Caddy.Search
SELECT *
  FROM (SELECT DISTINCT '2' DIV, (CASE WHEN A.START_TIME < '1130' THEN '1부' ELSE '2부' END) TEE_UP,
               (CASE WHEN A.START_TIME < '1130' THEN '1' ELSE '2' END) TEE_DIV,
               NVL(A.BOOKG_COURSE, '-') COURSE_NUM, C.COURSE_NAME,
               SUBSTR(A.START_TIME,1,2) || ':' || SUBSTR(A.START_TIME, -2, 2) START_TIME,
               NVL(BOOKG_NAME, ' ') AS BOOKG_NAME, NVL(BOOKG_MEMBER_CD, ' ') AS BOOKG_MEMBER_CD, CNT,
               NVL(CADDIE_NAME, ' ') AS CADDIE_NAME, NVL(D.CART_NO, '-') AS CART_NO,
               NVL(A.CADDIE_NO, '0') AS CADDIE_NO, A.TEAM_NO, 0 PERSON_CNT
          FROM VI_ALL_TEAMINFO A,
               (SELECT TEAM_NO, START_TIME, MAX(CART_NO) CART_NO, COUNT(*) CNT
                  FROM VI_ALL_TEAMINFO
                 WHERE COURSE_NAME IS NOT NULL
                 GROUP BY  TEAM_NO, START_TIME) B, CODE_WRAPPER C, CART_WRAPPER D
         WHERE A.TEAM_NO = A.TEAM_NO
           AND A.START_TIME = B.START_TIME
           AND A.COURSE_NAME = C.CODE_INDEX
           AND A.CART_NO = D.CART_ID
        UNION ALL
        SELECT '1' DIV, TEE_UP, TEE_DIV, COURSE_NUM, COURSE_NAME, START_TIME, MAX(BOOKG_NAME), MAX(BOOKG_MEMBER_CD), MAX(CNT), MAX(CADDIE_NAME),
               MAX(CART_NO), MAX(CADDIE_NO), MAX(TEAM_NO), COUNT(*)
          FROM (SELECT DISTINCT (CASE WHEN A.START_TIME < '1130' THEN '1부' ELSE '2부' END) TEE_UP,
                       (CASE WHEN A.START_TIME < '1130' THEN '1' ELSE '2' END) TEE_DIV,
                       NVL(A.BOOKG_COURSE, '-') COURSE_NUM, C.COURSE_NAME,
                       SUBSTR(A.START_TIME,1,2) || ':' || SUBSTR(A.START_TIME, -2, 2) START_TIME,
                       NVL(BOOKG_NAME, ' ') AS BOOKG_NAME, NVL(BOOKG_MEMBER_CD, ' ') AS BOOKG_MEMBER_CD, CNT,
                       NVL(CADDIE_NAME, ' ') AS CADDIE_NAME, NVL(D.CART_NO, '-') AS CART_NO,
                       NVL(A.CADDIE_NO, '0') AS CADDIE_NO, A.TEAM_NO
                  FROM VI_ALL_TEAMINFO A,
                       (SELECT TEAM_NO, START_TIME, MAX(CART_NO) CART_NO, COUNT(*) CNT
                          FROM VI_ALL_TEAMINFO
                         WHERE COURSE_NAME IS NOT NULL
                         GROUP BY  TEAM_NO, START_TIME) B, CODE_WRAPPER C, CART_WRAPPER D
                 WHERE A.TEAM_NO = A.TEAM_NO
                   AND A.START_TIME = B.START_TIME
                   AND A.COURSE_NAME = C.CODE_INDEX
                   AND A.CART_NO = D.CART_ID
                 ORDER BY  TEE_UP, TEE_DIV, COURSE_NUM, START_TIME) T1
         GROUP BY TEE_UP, TEE_DIV, COURSE_NUM, COURSE_NAME, START_TIME) S1
 ORDER BY TEE_UP, COURSE_NUM, COURSE_NAME, START_TIME, DIV 
 
$Common.Caddy2.Search
SELECT T1.TEAM_NO, T2.VISIT_NAME, T1.CADDIE_NO, T1.CADDIE_NAME, T1.CART_NO, T1.START_TIME, T2.CNT, T3.COURSE_NAME
  FROM (SELECT DISTINCT TEAM_NO, CADDIE_NO, CADDIE_NAME, CART_NO, START_TIME, COURSE_NAME FROM VI_ALL_TEAMINFO
         WHERE VISIT_DATE = TO_CHAR(SYSDATE, 'YYYYMMDD')) T1,
       (SELECT TEAM_NO, START_TIME, MAX(CASE WHEN SUBSTR(ID_NO, 5, 1) = 1 THEN VISIT_NAME END) VISIT_NAME, COUNT(*) CNT
          FROM VI_ALL_TEAMINFO
         WHERE COURSE_NAME IS NOT NULL AND VISIT_DATE = TO_CHAR(SYSDATE, 'YYYYMMDD')
         GROUP BY TEAM_NO, START_TIME) T2, CODE_WRAPPER T3
 WHERE T1.TEAM_NO = T2.TEAM_NO 
   AND T1.COURSE_NAME = T3.CODE_INDEX 
 ORDER BY T1.TEAM_NO

$Common.Caddy3.Search
SELECT *
  FROM (SELECT '1' DIV, T1.TEAM_NO, T2.VISIT_NAME, T1.CADDIE_NAME, T1.CADDIE_NO, T1.CART_NO, 
               SUBSTR(T1.START_TIME,1,2) || ':' || SUBSTR(T1.START_TIME, -2, 2) START_TIME, T2.CNT, T3.COURSE_NAME, '#ffeeee' COLOR
          FROM (SELECT MAX(TEAM_NO) TEAM_NO, CADDIE_NO, CADDIE_NAME, CART_NO, START_TIME, COURSE_NAME FROM VI_ALL_TEAMINFO
                 WHERE VISIT_DATE = TO_CHAR(SYSDATE, 'YYYYMMDD')
                 GROUP BY CADDIE_NO, CADDIE_NAME, CART_NO, START_TIME, COURSE_NAME) T1,
               (SELECT TEAM_NO, START_TIME, MAX(CASE WHEN SUBSTR(ID_NO, 5, 1) = 1 THEN VISIT_NAME END) VISIT_NAME, COUNT(*) CNT
                  FROM VI_ALL_TEAMINFO
                 WHERE COURSE_NAME IS NOT NULL AND VISIT_DATE = TO_CHAR(SYSDATE, 'YYYYMMDD')
                 GROUP BY TEAM_NO, START_TIME) T2, CODE_WRAPPER T3
         WHERE T1.TEAM_NO = T2.TEAM_NO 
           AND T1.COURSE_NAME = T3.CODE_INDEX) T1
 ORDER BY TEAM_NO, DIV

$Common.Caddy3.Detail.Search
SELECT DISTINCT '2' DIV, A.TEAM_NO, NVL(VISIT_NAME, ' ') AS VISIT_NAME, NVL(CADDIE_NAME, ' ') AS CADDIE_NAME, 
       NVL(A.CADDIE_NO, '0') AS CADDIE_NO, NVL(D.CART_NO, '-') AS CART_NO,
       SUBSTR(A.START_TIME,1,2) || ':' || SUBSTR(A.START_TIME, -2, 2) START_TIME, 0 CNT, C.COURSE_NAME, '#ffffff' COLOR
  FROM VI_ALL_TEAMINFO A,
       (SELECT TEAM_NO, START_TIME, MAX(CART_NO) CART_NO, COUNT(*) CNT
          FROM VI_ALL_TEAMINFO
         WHERE COURSE_NAME IS NOT NULL AND VISIT_DATE = TO_CHAR(SYSDATE, 'YYYYMMDD')
         GROUP BY  TEAM_NO, START_TIME) B, CODE_WRAPPER C, CART_WRAPPER D
 WHERE A.VISIT_DATE = TO_CHAR(SYSDATE, 'YYYYMMDD')
   AND A.TEAM_NO = B.TEAM_NO
   AND A.START_TIME = B.START_TIME
   AND A.COURSE_NAME = C.CODE_INDEX
   AND A.CART_NO = D.CART_ID
   AND A.TEAM_NO = :team_no

$마지막줄에 꼭 표시